import React from 'react';
import { Shield, Heart, Lock, Eye } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-black via-gray-900 to-black text-white">
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600/20 to-indigo-600/20 px-4 py-2 rounded-full border border-purple-500/30 mb-6">
            <Shield className="w-4 h-4 text-purple-400" />
            <span className="text-sm font-medium text-purple-300">Privacy First</span>
          </div>
          
          <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-indigo-400 bg-clip-text text-transparent mb-4">
            Privacy & Terms
          </h1>
          <p className="text-xl text-gray-300">
            Your inner world deserves the highest protection
          </p>
        </div>

        {/* Privacy Principles */}
        <div className="grid md:grid-cols-2 gap-8 mb-12">
          <div className="bg-gradient-to-br from-gray-900/50 to-black/50 p-6 rounded-xl border border-gray-700">
            <div className="flex items-center gap-3 mb-4">
              <Heart className="w-6 h-6 text-red-400" />
              <h2 className="text-xl font-semibold">Your Data, Your Story</h2>
            </div>
            <p className="text-gray-300 leading-relaxed">
              Your journal entries and personal reflections belong to you. We store them securely 
              and never share, sell, or analyze them beyond providing you with personalized insights.
            </p>
          </div>

          <div className="bg-gradient-to-br from-gray-900/50 to-black/50 p-6 rounded-xl border border-gray-700">
            <div className="flex items-center gap-3 mb-4">
              <Lock className="w-6 h-6 text-green-400" />
              <h2 className="text-xl font-semibold">Bank-Level Security</h2>
            </div>
            <p className="text-gray-300 leading-relaxed">
              All data is encrypted in transit and at rest. We use industry-standard security 
              practices to protect your personal information and emotional journey.
            </p>
          </div>
        </div>

        {/* Detailed Terms */}
        <div className="space-y-8">
          <section className="bg-gray-900/30 p-6 rounded-xl border border-gray-800">
            <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
              <Eye className="w-5 h-5 text-blue-400" />
              What We Collect
            </h2>
            <ul className="space-y-2 text-gray-300">
              <li>• Journal entries and reflections you create</li>
              <li>• Usage patterns to improve your experience</li>
              <li>• Account information for authentication</li>
              <li>• Emotional insights generated by AI for your personal use</li>
            </ul>
          </section>

          <section className="bg-gray-900/30 p-6 rounded-xl border border-gray-800">
            <h2 className="text-2xl font-semibold mb-4">How We Use Your Data</h2>
            <ul className="space-y-2 text-gray-300">
              <li>• Generate personalized AI insights and reflections</li>
              <li>• Track your emotional patterns and growth over time</li>
              <li>• Provide you with meaningful visualizations and analytics</li>
              <li>• Improve the app experience based on anonymized usage data</li>
            </ul>
          </section>

          <section className="bg-gray-900/30 p-6 rounded-xl border border-gray-800">
            <h2 className="text-2xl font-semibold mb-4">What We Never Do</h2>
            <ul className="space-y-2 text-gray-300">
              <li>• Share your personal journal content with third parties</li>
              <li>• Sell your data to advertisers or marketers</li>
              <li>• Use your content to train external AI models</li>
              <li>• Access your entries without explicit consent</li>
            </ul>
          </section>

          <section className="bg-gray-900/30 p-6 rounded-xl border border-gray-800">
            <h2 className="text-2xl font-semibold mb-4">Your Rights</h2>
            <ul className="space-y-2 text-gray-300">
              <li>• Export all your data in standard formats</li>
              <li>• Delete your account and all associated data</li>
              <li>• Control who can access your information</li>
              <li>• Opt out of data collection for app improvements</li>
            </ul>
          </section>

          <section className="bg-gray-900/30 p-6 rounded-xl border border-gray-800">
            <h2 className="text-2xl font-semibold mb-4">Beta Users</h2>
            <p className="text-gray-300 mb-3">
              During the beta period, anonymized usage patterns may be used to improve SoulScroll. 
              This includes:
            </p>
            <ul className="space-y-2 text-gray-300">
              <li>• Feature usage statistics (without personal content)</li>
              <li>• Performance metrics and error reporting</li>
              <li>• User interface interaction patterns</li>
            </ul>
            <p className="text-sm text-gray-400 mt-4">
              Your actual journal content remains private and is never used for development purposes.
            </p>
          </section>
        </div>

        {/* Contact */}
        <div className="text-center mt-12 p-6 bg-gradient-to-r from-purple-900/20 to-indigo-900/20 rounded-xl border border-purple-500/20">
          <h2 className="text-xl font-semibold mb-2">Questions or Concerns?</h2>
          <p className="text-gray-300">
            We're committed to transparency. Reach out through the feedback button or contact us directly.
          </p>
        </div>

        {/* Last Updated */}
        <div className="text-center mt-8">
          <p className="text-sm text-gray-400">
            Last updated: June 22, 2025
          </p>
        </div>
      </div>
    </div>
  );
}